services:
  - type: web
    name: semgrep-analysis-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python create_tables.py
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: GITHUB_APP_PRIVATE_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: semgrep-analysis-db
          property: connectionString
    envVarGroups:
      - name: semgrep-analysis-settings
    autoDeploy: true
    healthCheckPath: /health

databases:
  - name: semgrep-analysis-db
    plan: free
    databaseName: semgrep_analysis
    postgresMajorVersion: 15